#!/usr/bin/env node
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { checked } from '../lib/recheck.mjs';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
export function collectRechecks(root, today = new Date().toISOString().slice(0, 10)) {
  const rows = [];
  for (const slug of fs.readdirSync(path.join(root, 'companies')).filter(s => !s.startsWith('_'))) {
    const dir = path.join(root, 'companies', slug);
    if (!fs.statSync(dir).isDirectory()) continue;
    const sourcesPath = path.join(dir, 'sections/sources.json');
    const sources = fs.existsSync(sourcesPath) ? JSON.parse(fs.readFileSync(sourcesPath, 'utf8')).list : [];
    const url = n => { const s = sources.find(s => String(s.id) === String(n)); return s?.url || s?.link || s?.text?.match(/\]\((https?:[^\s]+)\)/)?.[1] || ''; };
    const scan = (obj, at) => {
      if (!obj || typeof obj !== 'object') return;
      if (obj.asOf) {
        const recheck = checked(obj.asOf, obj.recheck || (obj.type === 'trademark' ? '365d' : '90d'), today);
        rows.push({ slug, item: obj.label || obj.title || obj.key || at, value: obj.value ?? obj.text ?? '', ...recheck, sourceUrl: (obj.src || []).map(url).find(Boolean) || '' });
      }
      for (const [k, v] of Object.entries(obj)) scan(v, `${at}.${k}`);
    };
    for (const f of ['company.json', ...fs.readdirSync(path.join(dir, 'sections')).filter(f => f.endsWith('.json')).map(f => `sections/${f}`)]) scan(JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')), f);
  }
  return rows.sort((a, b) => a.due.localeCompare(b.due) || a.slug.localeCompare(b.slug) || a.item.localeCompare(b.item));
}
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const rows = collectRechecks(ROOT), cell = s => String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
  fs.mkdirSync(path.join(ROOT, 'data'), { recursive: true });
  fs.mkdirSync(path.join(ROOT, 'docs'), { recursive: true });
  fs.writeFileSync(path.join(ROOT, 'data/recheck.json'), JSON.stringify(rows, null, 2) + '\n');
  fs.writeFileSync(path.join(ROOT, 'docs/RECHECK.md'), '# Status rechecks\n\nGenerated by `npm run recheck` from dated company and section data.\n\n| Slug | Item | Value | As of | Window | Due | Overdue | Source |\n|---|---|---|---|---|---|---|---|\n' + rows.map(r => `| ${[r.slug, r.item, r.value, r.asOf, r.window, r.due, r.overdue ? 'yes' : 'no', r.sourceUrl ? `[Source](${r.sourceUrl})` : ''].map(cell).join(' | ')} |`).join('\n') + '\n');
  console.log(`recheck: ${rows.length} dated items, ${rows.filter(r => r.overdue).length} overdue`);
}
